package com.yuqirong.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHANNEL_ENTITY".
 */
public class ChannelEntity {

    private Long id;
    private String name;
    private String tId;
    private Boolean isSelect;

    public ChannelEntity() {
    }

    public ChannelEntity(Long id) {
        this.id = id;
    }

    public ChannelEntity(Long id, String name, String tId, Boolean isSelect) {
        this.id = id;
        this.name = name;
        this.tId = tId;
        this.isSelect = isSelect;
    }

    public ChannelEntity(String name, String tId, Boolean isSelect) {
        this.name = name;
        this.tId = tId;
        this.isSelect = isSelect;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTId() {
        return tId;
    }

    public void setTId(String tId) {
        this.tId = tId;
    }

    public Boolean getIsSelect() {
        return isSelect;
    }

    public void setIsSelect(Boolean isSelect) {
        this.isSelect = isSelect;
    }

    @Override
    public String toString() {
        return this.name;
    }
}
