package com.yuqirong.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RESULT_ENTITY".
 */
public class ResultEntity {

    private Long id;
    private String json;
    private String nId;

    public ResultEntity() {
    }

    public ResultEntity(Long id) {
        this.id = id;
    }

    public ResultEntity(Long id, String json, String nId) {
        this.id = id;
        this.json = json;
        this.nId = nId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public String getNId() {
        return nId;
    }

    public void setNId(String nId) {
        this.nId = nId;
    }

}
